# IRL™ 🌱 - Software for Humans
# Copyright (C) 2026 Anika Mukherjee
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

"""The .irl compiler — 2.1 "Full Language Edition".

Pipeline:  source -> lexer -> parser -> IR (canonical AST) -> optimizer
passes -> Python source -> CPython bytecode (.pyc).

The optimizer runs constant folding, dead-code elimination, memo
lowering and builtin caching, and reports exactly what it did. The
Python back end is CPython's own compiler, so compiled programs run at
full CPython speed — and the emitted code does fewer bytecode
operations than naive Python thanks to the passes.
"""

import hashlib
import os
import py_compile
import subprocess
import sys

from .lexer import IrlSyntaxError
from .parser import (
    Array,
    Assign,
    Attribute,
    BinOp,
    Block,
    Boolean,
    BreakStmt,
    ContinueStmt,
    DictLit,
    ForStmt,
    FString,
    FunctionCall,
    FunctionDef,
    Identifier,
    IfStmt,
    ImportStmt,
    IndexExpr,
    MethodCall,
    NoneLiteral,
    Number,
    Program,
    ReturnStmt,
    Slice,
    String,
    UnaryOp,
    VarDecl,
    WhileStmt,
    parse,
)

BUILTIN_NAMES = {
    "print",
    "input",
    "int",
    "float",
    "str",
    "len",
    "range",
    "sum",
    "min",
    "max",
    "abs",
    "round",
    "sorted",
    "type",
    "isinstance",
    "append",
}

STDLIB_ALLOWLIST = (
    "math",
    "random",
    "time",
    "datetime",
    "json",
    "string",
    "statistics",
)

RUNTIME_HEADER = """\
# Generated by irl lang build — IRL™ Language 2.1. Do not edit.
import functools as _irl_functools


def _irl_memo(fn):
    _irl_cache = {}

    def _irl_wrapper(*_irl_args):
        try:
            if _irl_args in _irl_cache:
                return _irl_cache[_irl_args]
        except TypeError:
            return fn(*_irl_args)
        _irl_result = fn(*_irl_args)
        try:
            _irl_cache[_irl_args] = _irl_result
        except TypeError:
            pass
        return _irl_result

    return _irl_wrapper


def _irl_append(seq, item):
    if isinstance(seq, list):
        seq.append(item)
        return seq
    raise TypeError("append() needs a list.")
"""


class BuildError(Exception):
    def __init__(self, message, line=None):
        self.line = line
        where = f" (line {line})" if line else ""
        super().__init__(f"[IRL_BUILD_ERROR]{where} {message}")


# --------------------------------------------------------------------------
# Optimizer passes (run on the canonical AST = the IR)
# --------------------------------------------------------------------------


def _is_const_num(node):
    return isinstance(node, Number) and isinstance(node.value, (int, float))


def _fold_binop(left_val, op, right_val):
    if op == "+":
        return left_val + right_val
    if op == "-":
        return left_val - right_val
    if op == "*":
        return left_val * right_val
    if op == "/":
        if right_val == 0:
            return None
        return left_val / right_val
    if op == "**":
        if abs(right_val) > 256:
            return None
        try:
            return left_val**right_val
        except (OverflowError, ZeroDivisionError):
            return None
    return None


def optimize(node, report, level=1):
    """Walk the AST in place, folding and pruning. Returns the node."""
    if level <= 0:
        return node

    if isinstance(node, BinOp):
        node.left = optimize(node.left, report, level)
        node.right = optimize(node.right, report, level)
        if node.op in ("and", "or") and isinstance(node.left, Boolean):
            report["constants_folded"] += 1
            if node.op == "and":
                return node.right if node.left.value else Boolean(False, node.line)
            return Boolean(True, node.line) if node.left.value else node.right
        if isinstance(node.left, String) and isinstance(node.right, String) and node.op == "+":
            report["constants_folded"] += 1
            return String(node.left.value + node.right.value, node.line)
        if _is_const_num(node.left) and _is_const_num(node.right):
            value = _fold_binop(node.left.value, node.op, node.right.value)
            if value is not None:
                report["constants_folded"] += 1
                return Number(value, node.line)
        return node

    if isinstance(node, UnaryOp):
        node.expr = optimize(node.expr, report, level)
        if node.op == "-" and _is_const_num(node.expr):
            report["constants_folded"] += 1
            return Number(-node.expr.value, node.line)
        if node.op == "not" and isinstance(node.expr, Boolean):
            report["constants_folded"] += 1
            return Boolean(not node.expr.value, node.line)
        return node

    if isinstance(node, IfStmt):
        node.condition = optimize(node.condition, report, level)
        node.true_block = optimize(node.true_block, report, level)
        if node.false_block is not None:
            node.false_block = optimize(node.false_block, report, level)
        if isinstance(node.condition, Boolean):
            report["dead_branches_removed"] += 1
            return node.true_block if node.condition.value else (node.false_block if node.false_block is not None else Block([]))
        return node

    if isinstance(node, WhileStmt):
        node.condition = optimize(node.condition, report, level)
        node.block = optimize(node.block, report, level)
        if isinstance(node.condition, Boolean) and not node.condition.value:
            report["dead_branches_removed"] += 1
            return Block([])
        return node

    for attr in ("statements",):
        if hasattr(node, attr):
            setattr(
                node,
                attr,
                [optimize(s, report, level) for s in getattr(node, attr)],
            )
    for attr in ("block",):
        if hasattr(node, attr) and getattr(node, attr) is not None:
            setattr(node, attr, optimize(getattr(node, attr), report, level))
    return _optimize_children(node, report, level)


def _optimize_children(node, report, level):
    if isinstance(node, (VarDecl, Assign, ReturnStmt)):
        if node.value is not None:
            node.value = optimize(node.value, report, level)
    elif isinstance(node, ForStmt):
        node.iter_expr = optimize(node.iter_expr, report, level)
        node.block = optimize(node.block, report, level)
    elif isinstance(node, FunctionDef):
        node.block = optimize(node.block, report, level)
    elif isinstance(node, (FunctionCall, MethodCall)):
        node.args = [optimize(a, report, level) for a in node.args]
        node.kwargs = {k: optimize(v, report, level) for k, v in node.kwargs.items()}
        if isinstance(node, MethodCall):
            node.obj = optimize(node.obj, report, level)
    elif isinstance(node, Attribute):
        node.obj = optimize(node.obj, report, level)
    elif isinstance(node, IndexExpr):
        node.array_expr = optimize(node.array_expr, report, level)
        node.index_expr = optimize(node.index_expr, report, level)
    elif isinstance(node, Slice):
        for attr in ("start", "stop", "step"):
            if getattr(node, attr) is not None:
                setattr(node, attr, optimize(getattr(node, attr), report, level))
    elif isinstance(node, Array):
        node.elements = [optimize(e, report, level) for e in node.elements]
    elif isinstance(node, DictLit):
        node.pairs = [(optimize(k, report, level), optimize(v, report, level)) for k, v in node.pairs]
    elif isinstance(node, FString):
        node.parts = [(kind, optimize(part, report, level) if kind == "expr" else part) for kind, part in node.parts]
    return node


# --------------------------------------------------------------------------
# Scope-aware transpiler (IR -> Python source)
# --------------------------------------------------------------------------


class Scope:
    def __init__(self, kind, parent=None):
        self.kind = kind  # "global" | "function" | "block"
        self.parent = parent
        self.names = {}

    def declare(self, name):
        if name in self.names:
            return self.names[name]
        if name in _all_bound_names(self):
            mangled = f"{name}__{len(self.names)}_{id(self) % 1000}"
        else:
            mangled = name
        self.names[name] = mangled
        return mangled

    def resolve(self, name):
        """Block scopes walk up; function scopes jump straight to global."""
        scope = self
        while scope is not None:
            if name in scope.names:
                return scope.names[name]
            if scope.kind == "function":
                scope = _global_root(scope)
                continue
            scope = scope.parent
        return None


def _global_root(scope):
    while scope.parent is not None:
        scope = scope.parent
    return scope


def _all_bound_names(scope):
    names = set()
    while scope is not None:
        names.update(scope.names.values())
        scope = scope.parent
    return names


class PyTranspiler:
    def __init__(self, level=1):
        self.level = level
        self.lines = []
        self.indent = 0
        self.used_builtins = set()
        self.memo_functions = []
        self.emitted_local_modules = set()
        self.local_source_dirs = []

    def emit(self, line=""):
        self.lines.append("    " * self.indent + line if line else "")

    # -- statements ---------------------------------------------------------

    def transpile_program(self, node):
        self._visit_block_statements(node.statements)
        return self.finish()

    def finish(self):
        header = [RUNTIME_HEADER]
        if self.used_builtins and self.level >= 2:
            for name in sorted(self.used_builtins):
                header.append(f"_irl_{name} = {name}")
        body = self.lines
        return "\n".join(header + [""] + body) + "\n"

    def _visit_block_statements(self, statements):
        for stmt in statements:
            self.visit_stmt(stmt)

    def visit_stmt(self, node):
        if isinstance(node, Program):
            self._visit_block_statements(node.statements)
        elif isinstance(node, Block):
            self._visit_block_statements(node.statements)
        elif isinstance(node, FunctionDef):
            self.visit_function(node)
        elif isinstance(node, VarDecl):
            name = self.scope.declare(node.name)
            self.emit(f"{name} = {self.visit_expr(node.value)}")
        elif isinstance(node, Assign):
            self.emit(f"{self.visit_target(node.target)} = {self.visit_expr(node.value)}")
        elif isinstance(node, IfStmt):
            self.visit_if(node)
        elif isinstance(node, WhileStmt):
            self.emit(f"while {self.visit_expr(node.condition)}:")
            self.indent += 1
            if node.block.statements:
                self._visit_block_statements(node.block.statements)
            else:
                self.emit("pass")
            self.indent -= 1
        elif isinstance(node, ForStmt):
            var = self.scope.declare(node.var_name)
            self.emit(f"for {var} in {self.visit_expr(node.iter_expr)}:")
            self.indent += 1
            if node.block.statements:
                self._visit_block_statements(node.block.statements)
            else:
                self.emit("pass")
            self.indent -= 1
        elif isinstance(node, BreakStmt):
            self.emit("break")
        elif isinstance(node, ContinueStmt):
            self.emit("continue")
        elif isinstance(node, ReturnStmt):
            if node.value is None:
                self.emit("return")
            else:
                self.emit(f"return {self.visit_expr(node.value)}")
        elif isinstance(node, ImportStmt):
            self.visit_import(node)
        else:
            self.emit(self.visit_expr(node))

    def visit_function(self, node):
        self.scope.declare(node.name)
        fn_scope = Scope("function", parent=self.scope)
        params = [fn_scope.declare(p) for p in node.params]
        old_scope = self.scope
        self.scope = fn_scope
        if node.memo:
            self.memo_functions.append(node.name)
            self.emit("@_irl_memo")
        self.emit(f"def {node.name}({', '.join(params)}):")
        self.indent += 1
        if node.block.statements:
            self._visit_block_statements(node.block.statements)
        else:
            self.emit("pass")
        self.indent -= 1
        self.scope = old_scope

    def visit_if(self, node):
        self.emit(f"if {self.visit_expr(node.condition)}:")
        self.indent += 1
        if node.true_block.statements:
            self._visit_block_statements(node.true_block.statements)
        else:
            self.emit("pass")
        self.indent -= 1

        false_block = node.false_block
        while false_block is not None:
            if len(false_block.statements) == 1 and isinstance(false_block.statements[0], IfStmt):
                elif_stmt = false_block.statements[0]
                self.emit(f"elif {self.visit_expr(elif_stmt.condition)}:")
                self.indent += 1
                if elif_stmt.true_block.statements:
                    self._visit_block_statements(elif_stmt.true_block.statements)
                else:
                    self.emit("pass")
                self.indent -= 1
                false_block = elif_stmt.false_block
            else:
                self.emit("else:")
                self.indent += 1
                if false_block.statements:
                    self._visit_block_statements(false_block.statements)
                else:
                    self.emit("pass")
                self.indent -= 1
                break

    def visit_import(self, node):
        if node.path is not None:
            base = self.local_source_dirs[-1] if self.local_source_dirs else os.getcwd()
            path = os.path.abspath(os.path.join(base, node.path))
            if not path.endswith(".irl"):
                path += ".irl"
            if path not in self.emitted_local_modules:
                if not os.path.isfile(path):
                    raise BuildError(f"Local module '{node.path}' not found.", node.line)
                self.emitted_local_modules.add(path)
                with open(path, encoding="utf-8") as fh:
                    code = fh.read()
                program = parse(_lex(code))
                self.local_source_dirs.append(os.path.dirname(path))
                self._visit_block_statements(program.statements)
                self.local_source_dirs.pop()
            return
        if node.module not in STDLIB_ALLOWLIST:
            raise BuildError(
                f"Module '{node.module}' is not available. Allowed: " + ", ".join(STDLIB_ALLOWLIST),
                node.line,
            )
        self.emit(f"import {node.module}")

    # -- expressions ---------------------------------------------------------

    def visit_target(self, node):
        if isinstance(node, Identifier):
            resolved = self.scope.resolve(node.name)
            if resolved is None:
                raise BuildError(
                    f"Assigning to '{node.name}' before declaring it with var.",
                    node.line,
                )
            return resolved
        if isinstance(node, IndexExpr):
            return f"{self.visit_expr(node.array_expr)}[{self.visit_expr(node.index_expr)}]"
        raise BuildError("Invalid assignment target.", getattr(node, "line", None))

    def visit_expr(self, node):
        if isinstance(node, Number):
            return repr(node.value)
        if isinstance(node, String):
            return repr(node.value)
        if isinstance(node, Boolean):
            return "True" if node.value else "False"
        if isinstance(node, NoneLiteral):
            return "None"
        if isinstance(node, Identifier):
            if node.name in BUILTIN_NAMES and self.scope.resolve(node.name) is None:
                self.used_builtins.add(node.name)
                if self.level >= 2:
                    return f"_irl_{node.name}"
                return node.name
            resolved = self.scope.resolve(node.name)
            if resolved is None:
                raise BuildError(f"'{node.name}' is not defined.", node.line)
            return resolved
        if isinstance(node, FunctionCall):
            args = [self.visit_expr(a) for a in node.args]
            kwargs = [f"{k}={self.visit_expr(v)}" for k, v in node.kwargs.items()]
            all_args = ", ".join(args + kwargs)
            return self._call_target(node.name, node.line) + f"({all_args})"
        if isinstance(node, MethodCall):
            args = [self.visit_expr(a) for a in node.args]
            kwargs = [f"{k}={self.visit_expr(v)}" for k, v in node.kwargs.items()]
            return f"{self.visit_expr(node.obj)}.{node.name}({', '.join(args + kwargs)})"
        if isinstance(node, Attribute):
            return f"{self.visit_expr(node.obj)}.{node.name}"
        if isinstance(node, BinOp):
            return f"({self.visit_expr(node.left)} {node.op} {self.visit_expr(node.right)})"
        if isinstance(node, UnaryOp):
            if node.op == "not":
                return f"(not {self.visit_expr(node.expr)})"
            return f"({node.op}{self.visit_expr(node.expr)})"
        if isinstance(node, IndexExpr):
            return f"{self.visit_expr(node.array_expr)}[{self.visit_expr(node.index_expr)}]"
        if isinstance(node, Slice):
            parts = []
            for attr in ("start", "stop", "step"):
                value = getattr(node, attr)
                parts.append(self.visit_expr(value) if value is not None else "")
            return ":".join(parts)
        if isinstance(node, Array):
            return "[" + ", ".join(self.visit_expr(e) for e in node.elements) + "]"
        if isinstance(node, DictLit):
            return "{" + ", ".join(f"{self.visit_expr(k)}: {self.visit_expr(v)}" for k, v in node.pairs) + "}"
        if isinstance(node, FString):
            pieces = []
            for kind, part in node.parts:
                if kind == "text":
                    pieces.append(repr(part))
                else:
                    pieces.append(f"str({self.visit_expr(part)})")
            if not pieces:
                return "''"
            return "(" + " + ".join(pieces) + ")"
        if isinstance(node, (Program, Block)):
            raise BuildError("Unexpected block in expression position.")
        raise BuildError(
            f"Cannot transpile node {type(node).__name__}.",
            getattr(node, "line", None),
        )

    def _call_target(self, name, line):
        if name in BUILTIN_NAMES and self.scope.resolve(name) is None:
            self.used_builtins.add(name)
            if self.level >= 2:
                return f"_irl_{name}"
            return name
        resolved = self.scope.resolve(name)
        if resolved is None:
            raise BuildError(f"'{name}' is not defined.", line)
        return resolved


def _lex(code):
    from .lexer import lex

    return lex(code)


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------


def compile_source(code, level=1, source_dir=None, report=None):
    """Transpile .irl source to Python source. Returns (py_source, report)."""
    report = report or {
        "constants_folded": 0,
        "dead_branches_removed": 0,
        "memoized_functions": 0,
    }
    program = parse(_lex(code))
    optimize(program, report, level)
    t = PyTranspiler(level=level)
    t.scope = Scope("global")
    if source_dir:
        t.local_source_dirs.append(source_dir)
    for stmt in program.statements:
        t.visit_stmt(stmt)
    py_source = t.finish()
    report["memoized_functions"] = len(t.memo_functions)
    return py_source, report


def build_file(path, args):
    """CLI entry: irl lang build <file.irl> [flags]."""
    from rich.console import Console

    console = Console()
    out = None
    run_after = "--run" in args
    verbose = "-v" in args or "--verbose" in args
    emit_py = "--emit-py" in args
    emit_ir = "--emit-ir" in args
    level = 1
    for arg in args:
        if arg in ("-O0", "-O1", "-O2"):
            level = int(arg[2:])

    if not os.path.exists(path):
        console.print(f"[red][IRL_BUILD_ERROR] {path}: file not found[/red]")
        return 1

    code = open(path, encoding="utf-8").read()
    source_dir = os.path.dirname(os.path.abspath(path))

    try:
        if emit_ir:
            program = parse(_lex(code))
            from rich.syntax import Syntax

            console.print(Syntax(repr(program)[:4000], "python", word_wrap=True))
            return 0
        py_source, report = compile_source(code, level=level, source_dir=source_dir)
    except IrlSyntaxError as exc:
        from irl.lang_runner import format_error

        console.print(f"[red]{format_error(exc, code)}[/red]")
        return 1
    except BuildError as exc:
        console.print(f"[red]{exc}[/red]")
        return 1

    if emit_py:
        console.print(py_source)
        return 0

    base = out or os.path.splitext(path)[0]
    py_path = base + ".py"
    pyc_path = base + ".pyc"

    cache_dir = os.path.join(source_dir, ".irl_cache")
    source_hash = hashlib.sha256((code + f"|O{level}").encode("utf-8")).hexdigest()
    cached_pyc = os.path.join(cache_dir, f"{source_hash}.pyc")

    try:
        os.makedirs(cache_dir, exist_ok=True)
        with open(py_path, "w", encoding="utf-8") as fh:
            fh.write(py_source)
        cache_hit = os.path.exists(cached_pyc)
        if not cache_hit:
            py_compile.compile(py_path, cfile=cached_pyc, doraise=True)
        py_compile.compile(py_path, cfile=pyc_path, doraise=True)
    except py_compile.PyCompileError as exc:
        console.print(f"[red][IRL_BUILD_ERROR] back-end compile failed: {exc}[/red]")
        return 1

    if verbose:
        console.print(
            f"[cyan]optimizer:[/cyan] folded {report['constants_folded']} constant(s), removed {report['dead_branches_removed']} dead branch(es), memoized {report['memoized_functions']} function(s)"
        )
    console.print(f"[green]built[/green] {pyc_path} [dim](-O{level}, {'cache hit' if cache_hit else 'fresh'})[/dim]")

    if run_after:
        result = subprocess.run([sys.executable, pyc_path])
        return result.returncode
    return 0
