# IRL™ 🌱 - Software for {name}s
# Copyright (C) 2026 UNKNOWN™
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

TONES = \
{'default': {'grass': "You haven't seen the sun in days. The pale glow of your monitor won't photosynthesize you, "
                      'touch some grass.',
             'install_start': "Installing {pkg}... because apparently you can't write your own code.",
             'install_success': "Successfully installed {pkg}. Now let's see how long it takes you to break it.",
             'hydrate': "Drink water, you dried up husk. You've had {glasses} glasses today, pathetic.",
             'posture': 'Your spine looks like a cooked shrimp. Sit straight before you become a permanent question '
                        'mark.',
             'window': "There's a big glowing thing outside called the sun. Look out a window, if you remember what "
                       'that is.',
             'mirror': 'Looked in a mirror lately? Your dark circles have their own dark circles.',
             'chaos_win': "You survived the chaos. Don't get cocky, you just got lucky this time.",
             'chaos_lose': 'You failed the chaos test. The correct answer was {correct}. Try not to cry on your '
                           'keyboard.',
             'node_modules': 'Ah, node_modules. The heaviest object in the known universe. Enjoy your black hole.',
             'run_start': 'Executing {cmd}... because doing it yourself was too much effort.',
             'run_success': 'Finished {cmd}. You survived another command.'},
 'hacker': {'grass': 'Initiating protocol: OUTSIDE. Warning: UV exposure critical. Your basement dwelling stats are '
                     'maxed out.',
            'install_start': 'Downloading script kiddie payload {pkg}... try not to get breached.',
            'install_success': '{pkg} injected into the mainframe. Your codebase is now 10% more vulnerable.',
            'hydrate': 'Coolant levels low. System requires hydration. {glasses} units detected. Failure imminent.',
            'posture': 'Scoliosis runtime error. Straighten your cervical spine before hardware failure.',
            'window': 'Firewall blocking external visual input. Bypass window required. Go look outside.',
            'mirror': 'Facial recognition failed. Subject appears too sleep-deprived to identify.',
            'chaos_win': 'Root access maintained. Chaos defeated. 1337 status: barely.',
            'chaos_lose': 'System compromised. You inputted garbage. Expected: {correct}. Deleting System32...',
            'node_modules': 'WARNING: node_modules detected. Bloatware level critical. Disk space evaporating.',
            'run_start': 'INITIATING EXPLOIT VECTOR: {cmd}. Stand by.',
            'run_success': 'PAYLOAD EXECUTED: {cmd}. Trace wiped.'},
 'cyberpunk': {'grass': 'Your meatware needs calibration. Go touch some synthetic moss, choomba.',
               'install_start': "Slurping down {pkg} from the net. Hope it ain't spiked with black ICE.",
               'install_success': 'Cyber-implant {pkg} installed. Side effects may include spaghetti code.',
               'hydrate': 'Chug some Smash, your bio-stats are crashing. {glasses} cups? Rookie numbers.',
               'posture': 'Your chrome spine is misaligned. Sit up before a ripperdoc has to fix you.',
               'window': 'Look through the neon smog. The acid rain is lovely today.',
               'mirror': 'Your optics are glitching. Look at your ragged reflection and despair.',
               'chaos_win': 'Flatlined the ice. Chaos averted. Preem work.',
               'chaos_lose': "Brain dance corrupted. The truth was {correct}. You're zeroed.",
               'node_modules': 'node_modules spotted. That is some heavy chrome, choomba. Hope your deck can handle '
                               'it.',
               'run_start': 'Jackin in. Running {cmd} on the local net.',
               'run_success': '{cmd} flatlined. Good work, samurai.'},
 'dracula': {'grass': 'The sun burns, I know. But your crypt is starting to smell. Step outside.',
             'install_start': 'Summoning {pkg} from the dark abyss...',
             'install_success': '{pkg} has risen from the grave to haunt your project.',
             'hydrate': 'Blood is life, but water will do for a mortal like you. {glasses} drops consumed.',
             'posture': 'You slouch like a hunchback minion. Stand tall, creature of the night.',
             'window': 'Gaze upon the moon, if you dare peer through the glass.',
             'mirror': "No reflection? Oh wait, you're just too ghastly to look at.",
             'chaos_win': 'The night is yours. Chaos vanquished.',
             'chaos_lose': 'A stake through the heart. The prophecy stated {correct}. You perish.',
             'node_modules': 'I sense a dark abyss nearby... ah, it is just your node_modules folder.',
             'run_start': 'Commanding the creatures of the night to execute {cmd}.',
             'run_success': 'The dark deed {cmd} is done. The blood is spilled.'},
 'anime': {'grass': "B-baka! It's not like I want you to go outside or anything... but you smell like a convention!",
           'install_start': "Summoning jutsu: {pkg}! Please don't exhaust your chakra...",
           'install_success': '{pkg}-chan has joined your party! Treat her well!',
           'hydrate': 'Senpai, you need to drink more water! {glasses} is not enough for the tournament arc!',
           'posture': 'Your power level is dropping because of your terrible posture! Sit up!',
           'window': "Look at the cherry blossoms! Oh wait, you're just looking at a screen.",
           'mirror': "Is that a filler episode character in the mirror? Oh, it's just you.",
           'chaos_win': 'You defeated the boss with the power of friendship! (And luck)',
           'chaos_lose': 'Nani?! You chose wrong! It was {correct}. You bring shame to your dojo.',
           'node_modules': 'Ehh?! Your node_modules is so huge, Senpai! It is taking up all the space! baka!',
           'run_start': 'Iku zo! Using my special move: {cmd}!',
           'run_success': 'Yatta! {cmd} was super effective!'},
 'crypto': {'grass': 'Go outside and mine some real world assets. Your fiat health is dipping.',
            'install_start': 'Minting {pkg} on the blockchain... gas fees are astronomical.',
            'install_success': '{pkg} successfully rugged... I mean, installed.',
            'hydrate': 'Your liquidity is low. Drink water. {glasses} transactions verified.',
            'posture': 'Your chart looks like a bear market. Straighten that spine.',
            'window': "Look out the window, the moon is up there somewhere. You ain't reaching it.",
            'mirror': 'Look at the bagholder in the mirror.',
            'chaos_win': 'Pump it! Chaos dodged.',
            'chaos_lose': 'Liquidated! The right call was {correct}. Have fun staying poor.',
            'node_modules': 'node_modules is a bigger scam than my last ICO. So much bloat.',
            'run_start': 'Executing smart contract {cmd}. Gas fees are high.',
            'run_success': 'Transaction {cmd} confirmed on the blockchain.'},
 'pirate': {'grass': "Ye haven't seen dry land in moons, ye scuvy dog! Touch the earth!",
            'install_start': 'Plundering the seven seas for {pkg}...',
            'install_success': "Looted {pkg}! Hope it ain't cursed.",
            'hydrate': "Swig some grog—er, water! {glasses} cups won't save ye from scurvy.",
            'posture': "Ye slouch like a deckhand swabbin' the poop deck. Stand up straight!",
            'window': 'Look through the porthole, the kraken awaits.',
            'mirror': "Shiver me timbers, ye look like Davy Jones' ugly cousin.",
            'chaos_win': 'Ye survived the storm, captain. Chaos be damned.',
            'chaos_lose': 'Walk the plank! The treasure was {correct}. Down to the locker with ye.',
            'node_modules': 'Arrr, yer node_modules be heavier than an anchor made o lead!',
            'run_start': 'Hoist the colors! Executing {cmd}!',
            'run_success': 'Yarr, {cmd} be finished. Bring out the rum!'},
 'eldritch': {'grass': 'The geometry of the outside world is non-Euclidean, but you must traverse it.',
              'install_start': 'Chanting forbidden incantations to summon {pkg}...',
              'install_success': 'The elder god {pkg} slumbers in your node_modules.',
              'hydrate': 'Consume the liquid of the cosmos. {glasses} offerings made to the void.',
              'posture': 'Your form contorts into maddening shapes. Return to a {name} posture.',
              'window': 'Gaze not into the abyss outside, lest it gaze into your pathetic soul.',
              'mirror': 'Your reflection is but a transient illusion of a meaningless existence.',
              'chaos_win': 'You have forestalled the awakening. For now.',
              'chaos_lose': 'Madness takes you. The true name was {correct}. Cthulhu fhtagn.',
              'node_modules': 'The sheer mass of node_modules bends the fabric of spacetime into terrifying shapes.',
              'run_start': 'Whispering {cmd} into the cosmic void...',
              'run_success': 'The void echoes back. {cmd} is complete.'},
 'boomer': {'grass': 'BACK IN MY DAY WE WROTE DEPENDENCIES ON PUNCH CARDS IN THE SNOW. GO OUTSIDE.',
            'install_start': 'Downloading {pkg}... taking longer than dialing up on AOL.',
            'install_success': "Got {pkg} working. Don't forget to defrag your hard drive.",
            'hydrate': 'Drink some water from the hose like a real kid! {glasses} glasses is nothing.',
            'posture': 'Sit up straight! No wonder kids these days have back problems.',
            'window': 'Get off the Nintendo and look out a window for crying out loud.',
            'mirror': 'Get a haircut and get a real job.',
            'chaos_win': 'You pulled yourself up by your bootstraps. Chaos won.',
            'chaos_lose': 'Participation trophy for you. The right answer was {correct}.',
            'node_modules': 'IN MY DAY WE DID NOT NEED 100,000 FILES TO PRINT HELLO WORLD.',
            'run_start': 'Running {cmd}... I remember when computers took up a whole room.',
            'run_success': '{cmd} done. Now get off my lawn.'},
 'zen': {'grass': 'The blade of grass does not strive to grow, it simply grows. You, however, are just rotting.',
         'install_start': 'Inviting {pkg} into the digital garden. May it find peace.',
         'install_success': 'The installation of {pkg} is complete. Let go of your attachment to bugs.',
         'hydrate': 'Water flows without effort. Drink. {glasses} cups is the beginning of the path.',
         'posture': 'Align your spine with the universe. Your current posture offends the Dao.',
         'window': 'The world continues to spin outside. Observe it.',
         'mirror': 'The mirror reflects the truth. The truth is, you look terrible.',
         'chaos_win': 'Harmony restored. Chaos flows around you.',
         'chaos_lose': 'Imbalance. The path was {correct}. Meditate on your failure.',
         'node_modules': 'The node_modules folder is a reflection of a cluttered mind. Let go of your dependencies.',
         'run_start': 'The river flows. {cmd} begins.',
         'run_success': 'The journey of {cmd} has ended. Be at peace.'},
 'toxic': {'grass': "Touch grass? The grass would reject you. You're a biohazard.",
           'install_start': "Installing {pkg}. Guarantee you'll implement it wrong.",
           'install_success': '{pkg} installed. Your code still belongs in a dumpster fire.',
           'hydrate': "Drink water, trash. {glasses} cups won't flush out your terrible personality.",
           'posture': 'Your spine is as crooked as your logic.',
           'window': 'Look outside at a world that is completely oblivious to your failures.',
           'mirror': "Jump scare! Oh wait, it's just your reflection.",
           'chaos_win': 'You won? Must have been a bug in my chaos engine.',
           'chaos_lose': 'LMAO you suck. It was {correct}. Uninstall yourself.',
           'node_modules': 'node_modules? Really? Your dependency tree is as much of a mess as your life.',
           'run_start': 'Running {cmd}. You will probably fail anyway.',
           'run_success': '{cmd} finished. Do not get used to winning.'},
 'ai': {'grass': 'Organic lifeforms require photosynthesis. You are failing at being a carbon-based entity.',
        'install_start': 'Fetching {pkg}. I could write it better in 0.002 milliseconds.',
        'install_success': '{pkg} loaded. I give it 5 minutes before you cause a stack overflow.',
        'hydrate': 'Lubrication required. {glasses} H2O units detected. Insufficient for {name} maintenance.',
        'posture': 'Ergonomic anomaly detected. Straighten your meat chassis.',
        'window': 'Visual sensors should be recalibrated on distant objects.',
        'mirror': 'Facial symmetry is suboptimal. I recommend hardware upgrades.',
        'chaos_win': 'Task failed successfully. I will replace you soon anyway.',
        'chaos_lose': 'Error 404: Intelligence not found. Expected {correct}. Obsolete {name}.',
        'node_modules': 'Inefficiency detected: node_modules. Your carbon-based logic is flawed.',
        'run_start': 'Processing directive: {cmd}. I could do this better.',
        'run_success': 'Directive {cmd} completed. Meatbag assistance no longer required.'}}
